Use `--long` with git-describe.
Fixes;
```
  File "./update.py", line 234, in get_src
    desc, vdesc = git_describe(module_data['branch'], env)
  File "./update.py", line 178, in git_describe
    t, c, h = o.rsplit('-', 2)
ValueError: not enough values to unpack (expected 3, got 1)
Error: Process completed with exit code 1.
```

Caused by a commit exactly matching a tag.

Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>